spring:
  application:
    name: show-service
  config:
    import: optional:configserver:http://localhost:8088
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/show_master
    username: root
    password: Password@254
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect				
server:
  port: 8085								
management:
  endpoints:
    web:
      exposure:
         include: refresh