server:
 port: 8089
spring:
  application:
    name: gaetway-service
  config:
    import: optional:configserver:http://localhost:8088
  profiles:
    active: dev 
  cloud:
    gateway:
      server:
       webmvc:
        routes:
         - id: show-service-route
           uri: lb://show-service
           predicates:
           - path=/shows/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultzone: http://localhost:8761/eureka/ 