spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tsl-desgin/omtbp-config-repo
          username: 
          password: 
server:

  port: 8888
