spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tsl-desgin/omtbp-config-repo
          username: tsl-design
          password: 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
server:
  port: 8888